# hosts/nix/configuration.nix — system-level config for the ThinkPad L480.
# Design / reasoning: docs/thinkpad-l480-setup.md
{ config, pkgs, ... }:

{
  imports = [ ./hardware-configuration.nix ];   # generated by nixos-generate-config — leave as-is

  # ---- Bootloader: systemd-boot (no GRUB, no LUKS) -----------------------
  boot.loader.systemd-boot.enable = true;
  boot.loader.systemd-boot.configurationLimit = 10;   # 10 generations fit comfortably in the 1 GB ESP (~50 MB each)
  boot.loader.efi.canTouchEfiVariables = true;

  # ---- Kernel + firmware -------------------------------------------------
  hardware.enableRedistributableFirmware = true;      # iwlwifi Wi-Fi firmware, etc.
  hardware.cpu.intel.updateMicrocode   = true;        # intel-ucode (needs the line above)

  # ---- Swap: 16 GB swapfile, declarative (no dd, no swap partition) ------
  swapDevices = [ { device = "/swapfile"; size = 16 * 1024; } ];   # size is in MB

  # ---- Networking --------------------------------------------------------
  networking.hostName = "nix";
  networking.networkmanager.enable = true;
  networking.firewall = {
    enable = true;
    # SSH is opened via services.openssh.openFirewall below.
    # When you `tailscale up`, uncomment to allow its UDP:
    # allowedUDPPorts = [ 41641 ];
  };

  # ---- Time / locale -----------------------------------------------------
  time.timeZone = "America/New_York";
  i18n.defaultLocale = "en_US.UTF-8";
  i18n.extraLocaleSettings = {
    LC_ADDRESS        = "en_US.UTF-8";
    LC_IDENTIFICATION = "en_US.UTF-8";
    LC_MEASUREMENT    = "en_US.UTF-8";
    LC_MONETARY       = "en_US.UTF-8";
    LC_NAME           = "en_US.UTF-8";
    LC_NUMERIC        = "en_US.UTF-8";
    LC_PAPER          = "en_US.UTF-8";
    LC_TELEPHONE      = "en_US.UTF-8";
    LC_TIME           = "en_US.UTF-8";
  };

  # ---- Graphics: Intel UHD 620 (i915 loads automatically) ----------------
  hardware.graphics.enable      = true;
  hardware.graphics.enable32Bit = true;
  hardware.graphics.extraPackages = with pkgs; [
    intel-media-driver     # newer codecs (Gen 8+)
    intel-vaapi-driver     # older MPEG/JPEG VAAPI paths
  ];

  # ---- GNOME desktop (Wayland, gdm) -------------------------------------
  services.xserver.enable = true;
  services.libinput.enable = true;            # ThinkPad TrackPoint + Touchpad
  services.displayManager.gdm.enable = true;
  services.desktopManager.gnome.enable = true;

  # Don't pull the GNOME apps we won't use (kitty is the only terminal; LibreWolf is the browser).
  environment.gnome.excludePackages = with pkgs; [
    epiphany             # GNOME Web
    geary                # mail
    gnome-console        # kitty is the only terminal
    gnome-contacts
    gnome-initial-setup
    gnome-music
    gnome-software       # no GUI store — we use nix
    gnome-tour
    gnome-calendar
    gnome-weather
    gnome-maps
    gnome-characters
    simple-scan
    totem                # video player
    yelp                 # help browser
  ];

  # ---- Audio: PipeWire (replaces PulseAudio) ----------------------------
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };

  # ---- Bluetooth ---------------------------------------------------------
  hardware.bluetooth.enable = false;   # off — not used; GNOME hides the toggle when no daemon

  # ---- Firmware updates via LVFS ----------------------------------------
  services.fwupd.enable = true;

  # ---- Power: GNOME's power-profiles-daemon ------------------------------
  # GNOME enables power-profiles-daemon (ppd) by default — it owns the
  # Balanced / Power-saver / Performance slider in gnome-control-center.
  # TLP is NOT used: NixOS hard-asserts TLP and ppd are mutually exclusive,
  # and ppd is the GNOME-integrated choice.

  # ---- Docker (manage containers directly) -------------------------------
  virtualisation.docker.enable = true;

  # ---- Tailscale: daemon enabled; `tailscale up` login is deferred -------
  services.tailscale.enable = true;

  # ---- SSH: enabled + locked to keys -------------------------------------
  services.openssh = {
    enable = true;
    openFirewall = true;                       # opens 22/tcp
    settings = {
      PermitRootLogin = "no";
      PasswordAuthentication = false;
      X11Forwarding = false;
    };
  };

  # ---- User (password set interactively during install via `nixos-enter` --
  # see README; no password material lives in this file or git) ------------
  users.users.zev = {
    isNormalUser = true;
    description  = "zev";
    extraGroups  = [ "wheel" "docker" "audio" "video" "networkmanager" ];
  };
  security.sudo.enable = true;            # wheel has sudo
  security.sudo.wheelNeedsPassword = false;   # passwordless sudo (any process as zev → instant root; deliberate)

  # ---- Unfree: needed for Obsidian (LibreWolf + Zed are free) ------------
  nixpkgs.config.allowUnfree = true;

  # ---- Nix: flakes on, plus weekly GC / auto-optimise --------------------
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  nix.gc = {
    automatic = true;
    dates = "weekly";
    options = "--delete-older-than 30d";
  };
  nix.optimise.automatic = true;

  # ---- nix-ld: restore the FHS dynamic linker NixOS omits, so curl-downloaded
  # prebuilt binaries run without patchelf. Escape hatch for tools not in nixpkgs. ----
  programs.nix-ld.enable = true;

  # ---- Fonts: JetBrains Mono Nerd Font (starship / tmux / kitty glyphs) --
  fonts.packages = with pkgs; [ nerd-fonts.jetbrains-mono ];

  # ---- Packages ----------------------------------------------------------
  environment.systemPackages = with pkgs; [
    # core CLI / shell
    vim bash-completion tmux git starship kitty fastfetch
    jq tree shellcheck dnsutils rsync curl wget man-pages just
    # media
    ffmpeg
    # Python + Node (no mise, no C toolchain — see docs)
    # pipx omitted: derivation fails to build on nixos-26.05 (2026-08); ad-hoc via `nix-shell -p pipx`.
    python3 nodejs
    # IDE — Zed (free software, built from source; renders via Vulkan/Mesa on UHD 620)
    zed-editor
    # k8s / homelab ops — backup-management set (argocd renders Helm in-cluster → no helm CLI;
    # kubeseal stays so this box can back up the Mac Mini's seal-and-commit workflow)
    kubectl k9s argocd kubeseal github-cli
    # networking / VPN
    tailscale
    # GUI apps (librewolf = free; obsidian = unfree)
    librewolf obsidian
    # nix tooling — LSP + formatter so Zed autocompletes/formats configuration.nix
    nil alejandra
    # AI CLI — opencode (SST's agent CLI)
    opencode
  ];

  # ---- Misc --------------------------------------------------------------
  programs.bash.completion.enable = true;

  # ---- Don't touch after install ----------------------------------------
  system.stateVersion = "26.05";   # set to the release you installed with; never change it
}
